#!/bin/sh
# Fake scp: last arg is host:dir (relative to $HOME); the others that exist are copied there, folders too.
eval dest=\${$#}; dir="$HOME/${dest#*:}"
n=$(($# - 1)); i=0
for f in "$@"; do i=$((i+1)); [ $i -le $n ] && [ -e "$f" ] && cp -R "$f" "$dir"; done
exit 0
